### ISSUE TITLE
接下来的翻译顺序是？

### ISSUE THREAD

**Issue by dear-lizhihua** [vuefe/vuefe.github.io#145]
vuex完事之后，预计还会翻译vue-resource、vue-loader、awesome-vue、ssr吧。

希望加入webpack官网翻译，以及前端相关书籍的翻译。

推荐优先翻译下面的热门书籍
https://leanpub.com/understandinges6
understanding es6
Nicholas C.Zakas著

https://leanpub.com/vuejs
The Majesty Of Vue.js
Alex Kyriakidis, Kostas Maniatis and Evan You

https://leanpub.com/exploring-es6
Exploring ES6
Axel Rauschmayer
这些书感觉都不错。感觉人多的话一本书一两个季度

**Comment by dingyiming** [comment]
我的想法是
- vue-resource
- vue-loader
- ssr

然后再看看还有什么 Vue文档需要翻译的，再考虑 Webpack吧，特别是 Webpack 2 改变不少

**Comment by viko16** [comment]
可以考虑 vuejs-templates/webpack 的文档翻译。

**Comment by dear-lizhihua** [comment]
https://github.com/vuejs/vue-validator

**Comment by dingyiming** [comment]
@dear-lizhihua 这周末我们再新开个计划试试看

**Comment by dear-lizhihua** [comment]
@viko16 
你是说这个文档吗？
https://github.com/vuejs-templates/webpack/blob/master/docs/SUMMARY.md

**Comment by viko16** [comment]
@dear-lizhihua 是的

**Comment by dear-lizhihua** [comment]
线上：http://webpack.vuefe.cn
仓库：https://github.com/vuefe/webpack.js.org
webpack 2.0的翻译已经开始了，大家有兴趣的参与进来吧。
