### ISSUE TITLE
迁移相关文档的用词规范建议 - migration.md

### ISSUE THREAD

**Issue by dear-lizhihua** [vuefe/vuefe.github.io#203]
[migration.html](http://vuefe.cn/guide/migration.html)
[migration-vue-router.html](http://vuefe.cn/guide/migration-vue-router.html)
[migration-vuex](http://vuefe.cn/guide/migration-vuex.html)

翻译迁移相关文档时，看到都有这几个词，建议规范：
- deprecated -> 废弃/弃用
- migration guide -> 迁移指南
- migration helper -> 迁移工具/迁移助手
- Upgrade Path -> 升级方式/升级路径

大家讨论下用哪个词比较好

**Comment by fytriht** [comment]
弃用 / 迁移指南 / 迁移助手 / 升级路径
个人觉得这四个词比较好。

**Comment by dear-lizhihua** [comment]
废弃或许更常用些
升级路径给人感觉很专业，不利于理解，升级方式就口语化多了。

**Comment by fytriht** [comment]
似乎 升级方式/升级路径 在中文语境下都不能很好表达原文意思，要不直接用 Upgrade Path 好了？

**Comment by dear-lizhihua** [comment]
是啊。这个Path不好翻译。不知道其他人有什么意见。
