### ISSUE TITLE
中文站侧边栏点击后页内跳转失效。

### ISSUE THREAD

**Issue by duncup** [vuefe/vuefe.github.io#252]
浏览器：Safari
浏览器版本：10.0.1
控制台提示：`TypeError: null is not an object (evaluating 't.offsetParent')`

**Comment by duncup** [comment]
PS：英文站无异常情况。

**Comment by dear-lizhihua** [comment]
在iPhone 5s Safari和Nexus 6上也无法点击，是英文文档站点的bug。
