### ISSUE TITLE
Pull request & Fork公告

### ISSUE THREAD

**Issue by 70data** [vuefe/vuefe.github.io#262]
[vuefe.github.io](https://github.com/vuefe/vuefe.github.io) 此仓库的 2.0-cn 分支，被推送为 Vue 官方中文翻译，官方 cn 仓库链接： [cn.vuejs.org](https://github.com/vuejs/cn.vuejs.org) 。

小伙伴们有什么翻译问题，或者是新增翻译内容，还是希望能提交 pr 到本仓库，我们会每天merge并推送至官方仓库 [cn.vuejs.org](https://github.com/vuejs/cn.vuejs.org) 。此事由 [dingyiming](https://github.com/dingyiming) 负责。

[vuefe.github.io](https://github.com/vuefe/vuefe.github.io) 此仓库会实时同步官方 en 站点内容，保持同步更新。

官方 cn 站点的内容会比这个仓库的略慢一点，而且内容会比这仓库少一点，但会更官方正式一点。

如果有任何翻译疑问，或者是不准确的地方，也可以直接 fork 官方仓库，并及提交 pr 。

**Comment by HerbertKarajan** [comment]
ok

**Comment by fzhw88** [comment]
新人不会pr，反馈一个翻译遗漏。
https://cn.vuejs.org/guide/instance.html#实例生命周期
实例生命周期这个部分，英文文档里第一部分有一段说明，中文漏掉了。

**Comment by crowphy** [comment]
翻译API ignoredElements的pr已提交
