### ISSUE TITLE
深入响应式原理 小问题

### ISSUE THREAD

**Issue by shellphon** [vuefe/vuefe.github.io#291]
注释里本意是输出对应的内容，原本内容是英文，注释输出却翻译成了中文，有点混淆感
`Vue.component('example', {
  template: '<span>{{ message }}</span>',
  data: function () {
    return {
      message: '没有更新'
    }
  },
  methods: {
    updateMessage: function () {
      this.message = '更新完成'
      console.log(this.$el.textContent) // => '没有更新'
      this.$nextTick(function () {
        console.log(this.$el.textContent) // => '更新完成'
      })
    }
  }
})`

**Comment by dear-lizhihua** [comment]
嗯。没仔细看，还原回去了。
