### ISSUE TITLE
vuex中的state翻译错误

### ISSUE THREAD

**Issue by mygaochunming** [vuefe/vuefe.github.io#296]
翻译：
computed: mapState([
  // 映射 state.count 到 store.this.count
  'count'
])
是不是应该是：
computed: mapState([
  // 映射 store.state.count 到 this.count
  'count'
])

**Comment by dingyiming** [comment]
具体是什么地方的？好像不是vuefe.cn目前vue文档中的吧？

**Comment by dear-lizhihua** [comment]
嗯，应该是当时弄反了，等我有时间再仔细校对下。
state 是从 store.state.count => this.count。
action 正好是反过来，从 this.increment() => this.$store.dispatch('increment')。
