### ISSUE TITLE
列表渲染章节部分，缺少'v-for with v-if'

### ISSUE THREAD

**Issue by Lesty612** [vuefe/vuefe.github.io#338]
**中文文档**
![image](https://cloud.githubusercontent.com/assets/12771548/24179309/4f37357c-0ee9-11e7-8916-5d29a7f645b1.png)
**英文文档**
![image](https://cloud.githubusercontent.com/assets/12771548/24179317/6976e022-0ee9-11e7-9d9f-20b3591da37f.png)

`list.md`文件里是有这一节的，就是不知道为什么中文文档里没有显示出来

**Comment by 70data** [comment]
已修复
